all:
  children:
    odoo:
      hosts:
        odoo-prod-18 (192.168.56.32):
          ansible_host: 192.168.56.32
          compose_project_name: client_prod_18
          deployment_target: dev
          odoo_version: 18
          odoo_exposed_port: 8069
          domain: odoo.example.com
      vars:
        deployment_path: /opt/docker
        auto_install_modules: true
        auto_update_modules: true
        force_rebuild: false
        optional_whisper: true
        cliente_name: "Cliente Producción"
