all:
  children:
    odoo_servers:
      hosts:
        192.168.56.32:
          deployment_path: /opt/odoo/production
          compose_project_name: client_prod_18
          deployment_target: dev
          odoo_version: 18
          odoo_exposed_port: 8069

        192.168.56.33:
          deployment_path: /opt/odoo/development
          compose_project_name: client_dev_18
          deployment_target: dev
          odoo_version: 18
          odoo_exposed_port: 8070