all:
  children:
    odoo:
      hosts:
        dv-erp-24.9 (192.168.24.9):
          ansible_host: 192.168.24.9
          compose_project_name: erp
          deployment_target: prod
          odoo_version: 18
          odoo_exposed_port: 8069
          domain: erp.doovate.com
          deployment_path: /opt/docker
          auto_install_modules: true
          auto_update_modules: true
          auto_create_database: true
          force_rebuild: false
          optional_whisper: false